### ISSUE TITLE
Available to borrow exceeds bank available to borrow

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/rex-bank-frontend#4]
<img width="1382" alt="Screen Shot 2021-11-14 at 9 26 59 AM" src="https://user-images.githubusercontent.com/5077880/141685501-43b486a4-236f-4c2d-a55f-fe9b0fc0edba.png">
<img width="1400" alt="Screen Shot 2021-11-14 at 9 27 07 AM" src="https://user-images.githubusercontent.com/5077880/141685502-622ee18e-902c-42ba-9b0d-77ef5488687a.png">

**Comment by elvijsTDL** [comment]
I will try to take this one

**Comment by shreyaspapi** [comment]
I am assuming `Available to borrow` is calculated based on how much `RIC` you got. A solution would be to do a conditional render based on `Available for borrow` and `Actual number`. Whichever is lower is shown right?

**Comment by elvijsTDL** [comment]
@mikeghen Fixed in #10
![Screenshot 2021-12-13 at 01 30 38](https://user-images.githubusercontent.com/77115130/145734114-e606cd0a-d96b-463d-84ba-a12ff2bac75e.png)

Collateral locked for USDC 4.2 , shows 4 as it is in the bank
![Screenshot 2021-12-13 at 01 31 58](https://user-images.githubusercontent.com/77115130/145734120-e5f136ce-82ab-4242-9527-8de19d66f6cf.png)
